### ISSUE TITLE
Port to Python 3.7+

### ISSUE THREAD

**Issue by pmontrasio** [pmontrasio/whois-oracle#2]
Tests fail on Python 3.7+ with

```
$ ./test.sh 
E
======================================================================
ERROR: ratelimit.test_cool_down_tracker (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: ratelimit.test_cool_down_tracker
Traceback (most recent call last):
  File "/usr/lib/python3.8/sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/me/whois-oracle/test_pythonwhois/ratelimit/test_cool_down_tracker.py", line 3, in <module>
    from pythonwhois.ratelimit.cool_down_tracker import CoolDownTracker
  File "/home/me/whois-oracle/pythonwhois/__init__.py", line 1, in <module>
    from . import net, parse
  File "/home/me/whois-oracle/pythonwhois/parse.py", line 583, in <module>
    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]
  File "/home/me/whois-oracle/pythonwhois/parse.py", line 583, in <listcomp>
    registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes]
  File "/home/me/whois-oracle/pythonwhois/parse.py", line 239, in preprocess_regex
    regex = re.sub(r"\\s\*\(\?P<([^>]+)>\.\+\)", r"\s*(?P<\1>\S.*)", regex)
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.8/re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.8/re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.8/sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \s at position 0


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

```

https://stackoverflow.com/questions/58328587/python-3-7-4-re-error-bad-escape-s-at-position-0 gives the reason for the failure.

**Comment by pmontrasio** [comment]
Fixed with commit a861e40a8a0a3594f953d25f55a85ea506afcc88
